# Application
quarkus.application.name=berichtenlijst
quarkus.application.version=0.1.0

# HTTP
quarkus.http.port=8080

# OpenAPI / Swagger UI
quarkus.smallrye-openapi.path=/q/openapi
quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.info-title=FBS Berichtenlijst API
quarkus.smallrye-openapi.info-version=0.1.0

# Redis
quarkus.redis.hosts=redis://localhost:6379
quarkus.redis.devservices.enabled=false

# Magazijnen configuratie
magazijnen.instances.magazijn-a.url=http://localhost:8081
magazijnen.instances.magazijn-a.naam=Magazijn A
magazijnen.instances.magazijn-b.url=http://localhost:8082
magazijnen.instances.magazijn-b.naam=Magazijn B

# Notificatie Service
notificatie.service.url=http://localhost:8083

# Logging
quarkus.log.level=INFO
quarkus.log.category."nl.rijksoverheid.moz".level=DEBUG
