name: ClusterFuzzLite PR fuzzing
on:
  pull_request:
    branches: [main]

permissions: read-all

jobs:
  PR:
    runs-on: ubuntu-latest
    steps:
      - name: Build Fuzzers
        id: build
        uses: google/clusterfuzzlite/actions/build_fuzzers@884713d53f1a1d4672b8a5ff48c2baf0580e690c # v1
        with:
          language: jvm
      - name: Run Fuzzers
        id: run
        uses: google/clusterfuzzlite/actions/run_fuzzers@884713d53f1a1d4672b8a5ff48c2baf0580e690c # v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 300
          mode: code-change
          keep-unaffected-fuzz-targets: true
