name: Test Berichtenmagazijn

on:
  push:
    branches: ['feature/berichtenmagazijn-**', 'main']
  pull_request:
    paths:
      - 'services/berichtenmagazijn/**'
      - 'libraries/fbs-common/**'
      - 'pom.xml'
  workflow_dispatch:

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven
      - name: Compile
        run: ./mvnw compile -pl services/berichtenmagazijn -am -B -q
      - name: Test
        run: ./mvnw test -pl services/berichtenmagazijn -am -B
